### ISSUE TITLE
Errores en retorno de funciones

### ISSUE THREAD

**Issue by UlisesGascon** [GingerCode/gingercode.org#11]
**Indentación excesiva, solo se debe indentar una vez por bloque, linea 4.**
```gingercode
definir @A = 100
definir @B = 10
definir @resutado = #aleatorio @A y @B
	devolver @A / @B
```

**Comment by aitanadev** [comment]
La sintaxis no concuerda con niguna sentencia Ginger, el error de sitaxis que te devuelve es correcto 👍 , eso se traduciría como:
```
var a = 100;
var b = 10;
var resultado = aleatorio(a, b);
  return a/b;
```

Es decir, estás llamando a una función y a la vez intentando añadirle un cuerpo, lo cual no es posible. Creo que para el ejemplo que intentas componer si no me equivoco te sobra la última linea y result simplemente guarda el resultado correctamente.

**Comment by UlisesGascon** [comment]
Correcto! Fallo mio, Gracias @bifuer!!
