### ISSUE TITLE
operador "estrictamente igual"

### ISSUE THREAD

**Issue by UlisesGascon** [GingerCode/gingercode.org#14]
El `===` ya esta implementado pero no de manera verbal.

```gingercode
definir @numero1 = 1
definir @numero2 = 2

// igual que..
@condicion = @numero1 == @numero2
@condicion = @numero1 === @numero2
@condicion = @numero1 es igual que @numero2
@condicion = @numero1 igual que @numero2
@condicion = @numero1 igual @numero2
```

**Comment by aitanadev** [comment]
Si existe, utilizando "es" o "idéntico" (se podrían añadir versiones más largas como "es idéntico que" o "es idéntico a" etc)

Está es la lista actual de sinónimos para operadores lógicos:

var pLogics = [
	["OR","||"],["AND","&&"],["O","||"],["Y","&&"],
	["es mayor o igual que",">="],["mayor o igual que",">="],["mayor o igual",">="],
	["es menor o igual que","<="],["menor o igual que","<="],["menor o igual","<="],
	["es mayor que",">"],["mayor que",">"],["mayor",">"],
	["es menor que","<"],["menor que","<"],["menor","<"],
	["es distinto que","!="],["distinto que","!="],["distinto","!="],["no es","!=="],
	["es igual que","=="],["igual que","=="],["igual","=="],**["es","==="],["identico","==="]**
];

Lo añado al wiki ;)

**Comment by UlisesGascon** [comment]
@bifuer lo añades a la wiki? Gracias!!

**Comment by aitanadev** [comment]
👍
